spring.application.name=devlog

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.threads.virtual.enabled=true
spring.task.scheduling.enabled=true

groq.base-url=https://api.groq.com/openai/v1
groq.model=llama-3.3-70b-versatile
groq.max-tokens=1024
groq.temperature=0.7
groq.api-key=${GROQ_API_KEY:}